# Add comments to improve readability
# Proxy requests to the backend server
upstream backend {
    # Use the backend service running on port 4000
    server backend:4000;
}

# Proxy requests to the frontend server
upstream frontend {
    # Use the frontend service running on port 3000
    server frontend:3000;
}

server {
    # Listen on port 80 for incoming connections
    listen 80;

    # Specify the server name
    server_name 192.168.0.106;

    # Proxy requests starting with /api to the backend server
    location /api {
        # Forward the request to the backend server
        proxy_pass http://backend;

        # Set the HTTP version to 1.1
        proxy_http_version 1.1;

        # Set the necessary headers for WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;

        # Bypass the cache for WebSocket connections
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy all other requests to the frontend server
    location / {
        # Forward the request to the frontend server
        proxy_pass http://frontend;

        # Set the HTTP version to 1.1
        proxy_http_version 1.1;

        # Set the necessary headers for WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;

        # Bypass the cache for WebSocket connections
        proxy_cache_bypass $http_upgrade;
    }
}



